<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".template.config\**" />
    <Content Remove=".template.config\**" />
    <EmbeddedResource Remove=".template.config\**" />
    <None Remove=".template.config\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomoNow.Communications.Application\DomoNow.Communications.Application.csproj" />
    <ProjectReference Include="..\DomoNow.Communications.Infrastructure\DomoNow.Communications.Infrastructure.csproj" />
  </ItemGroup>

</Project>
